<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="./views/css/styles.css">
    <title>Chat Online - PHP</title>
</head>
<body>
<header>
    <h1>Chat Online - PHP</h1>
</header>
<nav>
    <ul>
        <li><a href="index.php">Inicio</a></li>
        <?php
        if($_SESSION['user']->getName()=="")
            echo '<li><a href="index.php?login">Iniciar Sesi&oacute;n</a></li>';
        else{
            if($_SESSION['user']->getRole()==1){
                echo '<li><a href="index.php?administration">Panel de administración</a></li> ';
            } 
            echo ' <li><a href="index.php?chatRoom">Salas de chat</a></li>';
            echo ' <li><a href="index.php?login&logout">Salir</a></li>';
        }
        ?>
    </ul>
</nav>

<main>
    <aside>
        <div class="connected-users">
            <ul>
                <?php
                foreach($usuariosConectados as $usuario){
                    echo'<li><a href="index.php?duo&id1='.$usuario->getIdUser().'&id2='.$_SESSION['user']->getIdUser().'">'.$usuario->getName().'<img src="images/checked.png"></a></li>';
                }
                ?>
            </ul>
        </div>
    </aside>

    <section>
         <nav>
            <ul>
                <?php
                    foreach($salas as $sala){
                        echo' <li><a href="index.php?chatRoom&id='.$sala->getIdRoom().'">Sala '.$sala->getIdRoom().'</a></li>';
                    }
                ?>
            </ul>
        </nav>
        <div class="chat-container">
            <div class="message-container">
                <?php
                    if(isset($messages)){
                        foreach($messages as $message){
                            echo '<div class="message">'.$message->getUser()->getName().': '.$message->getMsg().'</div>';
                        } 
                    }
                ?>
            </div>
            <!-- Hay que especificar a que sala enviamos cada mensaje -->
            <?php
            if(isset($_GET['id'])){
                echo'
                <form action="index.php?chatRoom&id='.$_GET['id'].'" method="post" id="writeComment">
                    <textarea rows=5 cols=50 name="message"></textarea>
                    <input type="submit" name="sendMessage" value="Enviar mensaje">
                </form>
                ';
            }
            ?>
        </div>
    </section>
</main>
<footer>
    <h5>&copy;2022 Juan Tom&aacute;s Romero, Jesús Muela, Antonio Ruiz</h5>
</footer> 
</body>
</html>