<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="./views/css/styles.css">
    <title>Chat Online - PHP</title>
</head>
<body>
<h1>Chat Online - PHP</h1>
<a href="index.php">Inicio</a> -

<?php
if($_SESSION['user']->getName()=="")
	echo '<a href="index.php?login">Iniciar Sesi&oacute;n</a></br>';
else{
	echo 'Bienvenido '.$_SESSION['user']->getName().' ';
    if($_SESSION['user']->getRole()==1){
	    echo ' - <a href="index.php?administration">Panel de administración</a> ';
	} 
    echo ' - <a href="index.php?chatRoom&id=1">Salas de chat</a>';
    echo ' - <a href="index.php?login&logout">Salir</a>';
}
/* to do:
Usuarios inactivos (Joteison)
Tabla nueva para las diferentes salas de chat
Formato chat (Antonio)
En el main aparecen las salas disponibles en un nav. Además de un botón para crear tu propio chat.
Al seleccionar sala te lleva a una nueva view donde se ve la sala (Jt+ a medias).
 */
?>
<nav>
    <h3>Salas de chat disponibles:</h3>
    <?php
    foreach($usuariosConectados as $usuario){
        echo'<li>'.$usuario->getName().'</li>';
        if(!$_SESSION['user']->getName()==""){
    ?> <!-- Ahora mismo no hay salas creadas, dejo esto como ejemplo de como se vería.
     ¿Dejamos una general básica? crear método que vea que salas hay existentes (done a falta de la nueva tabla).-->
        <form action="index.php?chatRoom&id= <?php echo $usuario->getIdUser() ?>" method="post">
            <input type="submit" name="openChat" value="Acceder a la sala">
        </form>
    <?php 
        }else{
        echo '<br><h3>¿Quieres participar en una sala de chat? <a href="index.php?login">¡Registrate!</a></h3>';
        }  
    }    
    ?>
</nav> </br>
<!--Esto debería aparecer sólo si no tiene una sala de chat creada. Si la tiene el boton debería ser
 "Acceder a tu sala de chat". Habría que hacer el método para que busque las salas existentes (JT+ done a falta de la nueva tabla) -->
<form action="" method="post">
    <input type="submit" name="createChat" value="Crea tu propia sala de chat">    
</form>
<footer>
    <h5>&copy;2022 Juan Tom&aacute;s Romero, Jesús Muela, Antonio Ruiz</h5>
</footer> 
</body>
</html>
