<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="./views/css/styles.css">
    <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
    <title>Chat Online - PHP</title>
</head>
<body class="text-center">
<h1 class="m-5">Chat Online - PHP</h1>
<a href="index.php">Inicio</a> -

<?php
if($_SESSION['user']->getName()=="")
	echo '<a href="index.php?login">Iniciar Sesi&oacute;n</a></br>';
else{
	echo 'Bienvenido '.$_SESSION['user']->getName().' ';
    if($_SESSION['user']->getRole()==1){
	    echo ' - <a href="index.php?administration">Panel de administración</a> ';
	} 
    echo ' - <a href="index.php?chatRoom&id=1">Salas de chat</a>';
    echo ' - <a href="index.php?login&logout">Salir</a>';
}
/* to do:
Usuarios inactivos (Joteison)
Tabla nueva para las diferentes salas de chat
Formato chat (Antonio)
En el main aparecen las salas disponibles en un nav. Además de un botón para crear tu propio chat.
Al seleccionar sala te lleva a una nueva view donde se ve la sala (Jt+ a medias).
 */
?>
<nav>
    <?php
    if($_SESSION['user']->getName()==""){
        echo '<br><h3>¿Quieres participar en una sala de chat? <a href="index.php?login">¡Registrate!</a></h3>';
    }
    ?>
</nav>
<footer>
    <h5 class="m-5">&copy;2022 Juan Tom&aacute;s Romero, Jesús Muela, Antonio Ruiz</h5>
</footer> 
</body>
</html>
